apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pearc26-impasta-rw-pv
